### ISSUE TITLE
Site needs an 'About' page

### ISSUE THREAD

**Issue by adamgpope** [FLamparski/seeraccept#4]
Though it's pretty pretty obvious what the site does, it could do with an 'about' page saying what the software does (privacy and all that useful info you have on the github main page) as well as contact details to get help/assistance. 

Links to portal submission criteria, average submission acceptance rates, all that guff, could also be useful.

**Comment by FLamparski** [comment]
Fixed in 1d378b9d by adding links to the README document from the app. Hope this helps!
